[project]
name = "webodm-admin"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["click", "requests", "dotenv"]

[project.scripts]
webodm-admin = "webodm_admin.workshop:webodm"

